### ISSUE TITLE
filled isn't accepting dyanamic / state value

### ISSUE THREAD

**Issue by Hamza-Sajid** [sandra-lewis/react-animated-rating#1]
I am getting errors while implementing the **<Rating component>** whenever I put the `_filled_` prop value as a value of state/variable.

It's working okay with direct initialized numbers e.g filled={1}
But an error on this **filled={rating}**
**rating here is a state which holds a number value of 2

I am using the following versions:
"react-animated-rating": "^1.0.5",
    "react-dom": "^18.2.0",

**Comment by sandra-lewis** [comment]
Hi Hamza,

Will look into it and find a fix.

Thanks.

**Comment by sandra-lewis** [comment]
This issue has now been fixed in v1.0.6.

**Comment by Hamza-Sajid** [comment]
Thanks
