### ISSUE TITLE
How to disable ?

### ISSUE THREAD

**Issue by codingwithashu** [sandra-lewis/react-animated-rating#2]
I want to disable rating on one of my page

**Comment by sandra-lewis** [comment]
@codingwithashu the disable feature has not been implemented in react-animated-rating v1.0.6. Will add it to the next release.

**Comment by codingwithashu** [comment]
When new release will come ?

**Comment by sandra-lewis** [comment]
@codingwithashu will try to make the next release by this Friday.

**Comment by codingwithashu** [comment]
Great thanks

**Comment by sandra-lewis** [comment]
@codingwithashu added the disable functionality. Please check the latest release v1.1.0. You can refer to the [demo](https://react-animated-rating.netlify.app/) for reference on how to use the `disabled` prop.

**Comment by codingwithashu** [comment]
thanks
